version: "3.8"

services:
    zookeeper:
        image: bitnami/zookeeper:latest
        ports:
            - 2181:2181
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: bitnami/kafka:latest
        ports:
            - 9092:9092
            - 9093:9093
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
        depends_on:
            - zookeeper
        healthcheck:
            test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list" ]
            interval: 5s
            timeout: 5s
            retries: 20

    database:
        image: postgres:14
        environment:
            - POSTGRES_DB=lebedev_credit_card
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
          test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d lebedev_credit_card'"]
          interval: 10s
          timeout: 3s
          retries: 6

    prometheus:
        image: prom/prometheus
        volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
        - "9090:9090"

    jaeger:
        image: jaegertracing/all-in-one
        ports:
        - "6831:6831/udp"
        - "16686:16686"

    api-gateway:
        build: .
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        ports:
            - 8000:8000
        environment:
            - AUTH_HOST=auth
            - AUTH_PORT=8001
            - TRANSACTIONS_HOST=transaction
            - TRANSACTIONS_PORT=8002
            - FACE_VERIFICATION_HOST=face_verification
            - FACE_VERIFICATION_PORT=8003
            - JAEGER_AGENT_HOST=jaegerrrrrr
            - JAEGER_AGENT_PORT=6831
            - JAEGER_SAMPLER_PARAM=1.0

        depends_on:
            database:
                condition: service_healthy


    auth:
        build: ./submodules/auth_service
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8001
        ports:
            - 8001:8001
        volumes:
            - ./fastapi_kafka/producer:/usr/src/app
            - photo-storage:/usr/photos
        environment:
            - KAFKA_HOST=kafka
            - KAFKA_PORT=9092
            - KAFKA_PRODUCER_TOPIC=lebedev_faces
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=database
            - DB_NAME=lebedev_credit_card
            - JAEGER_AGENT_HOST=jaeger
            - JAEGER_AGENT_PORT=6831
            - JAEGER_SAMPLER_PARAM=1.0
        depends_on:
            kafka:
                condition: service_healthy
            database:
                condition: service_healthy

    transaction:
        build: ./submodules/transaction_service
        command: >
            bash -c "alembic upgrade head
            && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8002"
        ports:
            - 8002:8002
        environment:
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=database
            - DB_NAME=lebedev_credit_card
            - JAEGER_AGENT_HOST=jaeger
            - JAEGER_AGENT_PORT=6831
            - JAEGER_SAMPLER_PARAM=1.0
        depends_on:
            database:
                condition: service_healthy

    face_verification:
        build: ./submodules/face_verification_service
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8003
        ports:
            - 8003:8003
        volumes:
            - ./fastapi_kafka/consumer:/usr/src/app
            - photo-storage:/usr/photos
        environment:
            - KAFKA_HOST=kafka
            - KAFKA_PORT=9092
            - KAFKA_CONSUMER_TOPIC=lebedev_faces
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=database
            - DB_NAME=lebedev_credit_card
        depends_on:
            kafka:
                condition: service_healthy
            database:
                condition: service_healthy

volumes:
    photo-storage:
