apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api-gateway.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SERVICE_NAME
              value: "{{ .Values.service_name }}"

            # auth
            - name: AUTH_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: auth_host
            - name: AUTH_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: auth_port

            # transactions
            - name: TRANSACTIONS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: transactions_host
            - name: TRANSACTIONS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: transactions_port

            # face verification
            - name: FACE_VERIFICATION_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: face_verification_host
            - name: FACE_VERIFICATION_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: face_verification_port
                  
            # Jaeger
            - name: JAEGER_AGENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.jaeger_cofigmap.name }}
                  key: jaeger_agent_host
            - name: JAEGER_AGENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.jaeger_cofigmap.name }}
                  key: jaeger_agent_port
