version: '3'

services:
  gateway:
    container_name: 'APIGateway-Lebedev'
    build:
      context: app/
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - '28080:8080'
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - PYTHONPATH=/workspace/src
