apiVersion: apps/v1
kind: Deployment
metadata:
  name: lebedev-api-gateway-deployment
  labels:
    app: lebedev-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lebedev-api-gateway
  template:
    metadata:
      labels:
        app: lebedev-api-gateway
    spec:
      containers:
      - name: lebedev-api-gateway-container
        image: kotbegemott/api-gateway-service:2
        ports:
          - containerPort: 8000
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 2
          successThreshold: 2
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 2
          failureThreshold: 5
        env:
        - name: AUTH_HOST
          valueFrom:
            configMapKeyRef:
              name: lebedev-api-gateway-configmap
              key: auth_host
        - name: AUTH_PORT
          valueFrom:
            configMapKeyRef:
              name: lebedev-api-gateway-configmap
              key: auth_port

        - name: TRANSACTIONS_HOST
          valueFrom:
            configMapKeyRef:
              name: lebedev-api-gateway-configmap
              key: transactions_host
        - name: TRANSACTIONS_PORT
          valueFrom:
            configMapKeyRef:
              name: lebedev-api-gateway-configmap
              key: transactions_port

        - name: FACE_VERIFICATION_HOST
          valueFrom:
            configMapKeyRef:
              name: lebedev-api-gateway-configmap
              key: face_verification_host
        - name: FACE_VERIFICATION_PORT
          valueFrom:
            configMapKeyRef:
              name: lebedev-api-gateway-configmap
              key: face_verification_port
